services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: 'mysql:8'
    environment:
      MYSQL_ROOT_PASSWORD: nexus123
      MYSQL_DATABASE: football
    ports:
      - '3336:3306'
    volumes:
      - 'database_data:/var/lib/mysql'
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
  database_test:
    image: 'mysql:8'
    environment:
      MYSQL_ROOT_PASSWORD: nexus123
      MYSQL_DATABASE: football_test # A different database name for testing
    ports:
      - '3337:3306' # Optional: use a different port to avoid conflicts with the main database
    volumes:
      - 'database_test_data:/var/lib/mysql'
volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
  database_test_data:
###< doctrine/doctrine-bundle ###
